version: '3.3'

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: tetyorkin/foodgram-project:latest
    restart: always
    volumes:
      - ./static:/code/static/
      - ./media:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19
    restart: always
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static/
      - ./media:/code/media/
