# Generated by Django 3.1.7 on 2021-04-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredients', to='recipes.recipe'),
        ),
    ]
