# Generated by Django 3.1.7 on 2021-04-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210422_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='count',
            field=models.IntegerField(),
        ),
    ]
